apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: gitsecops
  name: deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gitsecops
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: gitsecops
    spec:
      restartPolicy: Always
      containers:
      - name: gitsecops
        image: dllhb/gotc-gitops:v0.0.1
        imagePullPolicy: Always
        envFrom:
          - secretRef:
              name: secret-env
        ports:
        - containerPort: 9999
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: "100m"
            memory: 128Mi
          requests:
            cpu: 50m
            memory: 64Mi
