apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: devsecops
  name: deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: devsecops
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: devsecops
    spec:
      restartPolicy: Always
      containers:
      - name: devsecops
        image: dllhb/devopsday:v0.8
        imagePullPolicy: Always
        ports:
        - containerPort: 9999
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: "200m"
            memory: 256Mi
          requests:
            cpu: 100m
            memory: 128Mi
