apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  app: gitsecops

resources:
- deployment.yaml
- service.yaml

namespace: gitops-argocd

generators:
 - ./kops-secret.yaml


generatorOptions:
  labels:
    deploy.type: kustomize
  disableNameSuffixHash: true
