apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  app: devsecops
resources:
- deployment.yaml
- service.yaml

namespace: gitops-argocd


generatorOptions:
  labels:
    deploy.type: kustomize
  disableNameSuffixHash: true
